"""empty message

Revision ID: 8a82999a6ce1
Revises: 
Create Date: 2020-09-05 11:49:48.305689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a82999a6ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informationand_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Introduction', sa.String(length=500), nullable=False),
    sa.Column('Introduction_en', sa.String(length=500), nullable=False),
    sa.Column('phonenumber', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    op.add_column('service', sa.Column('content_Font_size', sa.Integer(), nullable=False))
    op.add_column('service', sa.Column('title_Font_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'title_Font_size')
    op.drop_column('service', 'content_Font_size')
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('informationand_records')
    # ### end Alembic commands ###
