"""empty message

Revision ID: db01c82d6651
Revises: 
Create Date: 2020-09-15 15:32:47.358066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db01c82d6651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information_and__records', sa.Column('Introduction_font_color', sa.Text(), nullable=True))
    op.add_column('information_and__records', sa.Column('Main_page_intro_details_font_color', sa.Text(), nullable=True))
    op.add_column('information_and__records', sa.Column('Main_page_intro_font_color', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('content_font_color', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('title_font_color', sa.Text(), nullable=True))
    op.add_column('sub_service', sa.Column('content_font_color', sa.Text(), nullable=True))
    op.add_column('sub_service', sa.Column('title_font_color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_service', 'title_font_color')
    op.drop_column('sub_service', 'content_font_color')
    op.drop_column('service', 'title_font_color')
    op.drop_column('service', 'content_font_color')
    op.drop_column('information_and__records', 'Main_page_intro_font_color')
    op.drop_column('information_and__records', 'Main_page_intro_details_font_color')
    op.drop_column('information_and__records', 'Introduction_font_color')
    # ### end Alembic commands ###
